[project]
name = "nonebot-plugin-picstatus"
dynamic = ["version"]
description = "A NoneBot2 plugin generates a picture which shows the status of current device"
authors = [
    { name = "LgCuwukii", email = "lgc2333@126.com" },
    { name = "wyf9", email = "wyf9@wyf9.top" },
]
dependencies = [
    "nonebot2>=2.5.0",
    "nonebot-plugin-apscheduler>=0.5.0",
    "nonebot-plugin-alconna>=0.62.1",
    "nonebot-plugin-uninfo>=0.11.1",
    "nonebot-plugin-htmlrender>=0.6.7,<0.8",
    "nonebot-plugin-localstore>=0.7.4",
    "cookit[jinja,loguru,playwright,pydantic,nonebot-localstore]>=0.13.3",
    "psutil>=7.2.2",
    "py-cpuinfo>=9.0.0",
    "anyio>=4.14.2",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "yarl>=1.24.5",
    "taskgroup>=0.2.2; python_version<'3.11'",
]
requires-python = ">=3.10,<4.0"
readme = "README.md"
license = { text = "MIT" }

[project.urls]
homepage = "https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "nonebot_plugin_picstatus/__init__.py"

[tool.poe.tasks]
test.cmd = "uv run pytest"
coverage.cmd = "uv run pytest --cov=nonebot_plugin_picstatus --cov-branch --cov-report=term-missing"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "session"
